import SwiftUI
import MapKit
import CoreLocation

struct Location: Identifiable {
    let id = UUID()
    let name: String
    let latitude: Double
    let longitude: Double
    let color: Color
    var description: String?
    var symbol: String?
    var distance: Double?
}

let locations: [Location] = [
    // 🔴 Events
    Location(name: "Highland Games", latitude: 56.8169, longitude: -5.1128, color: .red, description: "A traditional celebration of Scottish culture featuring strength events like caber tossing and hammer throwing, along with piping and Highland dancing, held across Scotland.", symbol: "figure.disc.sports"),
    Location(name: "Edinburgh Fringe Festival", latitude: 55.9543, longitude: -3.1893, color: .red, description: "The world’s largest arts festival, with thousands of performances in theater, comedy, and music, transforming Edinburgh into a creative hub.", symbol: "theatermask.and.paintbrush.fill"),
    Location(name: "Tall Ships Races", latitude: 57.1499, longitude: -2.0938, color: .red, description: "An international sailing event where large traditional ships gather in Scottish ports. Visitors can see the vessels up close, explore some onboard, and experience related maritime events and activities.", symbol: "sailboat.fill"),
    Location(name: "Beltane Fire Festival", latitude: 55.9533, longitude: -3.1883, color: .red, description: "A modern revival of an ancient Celtic celebration marking the arrival of summer. Held on Calton Hill in Edinburgh, it features fire displays, drumming, and performances inspired by folklore and mythology.", symbol: "flame.fill"),
    Location(name: "Royal Edinburgh Military Tattoo", latitude: 55.9496, longitude: -3.1999, color: .red, description: "A renowned military spectacle held at Edinburgh Castle, featuring performances by Scottish regiments, marching bands, and international acts, all set against the stunning backdrop of the castle.", symbol: "crown.fill"),
    Location(name: "Edinburgh International Festival", latitude: 55.9533, longitude: -3.1889, color: .red, description: "A world-class celebration of the arts, featuring opera, theater, classical music, and dance performances from top artists and companies, held annually in Edinburgh.", symbol: "music.quarternote.3"),
    Location(name: "Samhuinn Fire Festival", latitude: 55.9543, longitude: -3.1883, color: .red, description: "A dramatic reenactment of ancient Celtic rituals marking the transition from summer to winter. Held on Calton Hill in Edinburgh, it combines fire displays, dance, and storytelling based on Scottish folklore.", symbol: "flame.fill"),
    Location(name: "Glasgow Whisky Festival", latitude: 55.8652, longitude: -4.2518, color: .red, description: "A celebration of Scotland’s national drink, featuring tastings from top distilleries, masterclasses, and expert-led sessions. It’s a must-visit for whisky enthusiasts looking to explore a variety of blends and single malts.", symbol: "wineglass.fill"),
    Location(name: "Edinburgh Hogmanay", latitude: 55.9533, longitude: -3.1873, color: .red, description: "Scotland’s famous New Year celebration, featuring a massive street party, live music, a torchlight procession, and a spectacular fireworks display over Edinburgh Castle to ring in the new year.", symbol: "fireworks"),
    Location(name: "Edinburgh International Science Festival", latitude: 55.9510, longitude: -3.1910, color: .red, description: "A celebration of science and innovation with interactive exhibits, workshops, and talks. It brings together experts and visitors of all ages to explore the wonders of science in engaging and fun ways.", symbol: "graduationcap.fill"),
    Location(name: "Glasgow International Comedy Festival", latitude: 55.8642, longitude: -4.2518, color: .red, description: "Scotland’s largest comedy festival, featuring performances from top comedians and emerging talent. It offers a mix of stand-up, improv, and theatrical comedy across various venues in Glasgow.", symbol: "quote.bubble.fill"),
    Location(name: "St Andrew's Day", latitude: 56.4907, longitude: -2.8013, color: .red, description: "Scotland’s national day, celebrated on November 30th in honor of Saint Andrew. It features traditional music, Scottish cuisine, and cultural events across the country, marking Scotland's heritage and pride.", symbol: "flag.fill"),
    Location(name: "Slamdunk Festival", latitude: 55.8625, longitude: -4.2518, color: .red, description: "A popular UK music festival featuring top punk, rock, and alternative bands. Held in multiple cities, it’s known for its high-energy performances and vibrant atmosphere, attracting music fans from all over.", symbol: "music.quarternote.3"),
    Location(name: "The Scottish Open", latitude: 56.1141, longitude: -3.9466, color: .red, description: "A prestigious golf tournament held annually in Scotland, attracting top international players. It’s part of the European Tour and offers a chance to see world-class golf against the backdrop of Scotland's scenic courses.", symbol: "figure.golf"),
    Location(name: "Tartan Day Parade", latitude: 55.8650, longitude: -4.2570, color: .red, description: "A celebration of Scottish heritage, held annually in various cities, with the largest in New York. The parade features bagpipers, dancers, and pipers, all proudly showcasing Scotland's iconic tartan and culture.", symbol: "globe.europe.africa.fill"),
    Location(name: "Burns Night", latitude: 55.8781, longitude: -4.3100, color: .red, description: "A celebration of Scotland’s national poet, Robert Burns, held on January 25th. It includes reciting his poetry, enjoying traditional Scottish dishes like haggis, and toasting with whisky in his honor.", symbol: "scroll.fill"),
    Location(name: "Scottish Borders Walking Festival", latitude: 55.7075, longitude: -2.7710, color: .red, description: "An annual event celebrating the region's stunning landscapes. It offers guided walks through picturesque hills, valleys, and historic sites, perfect for nature lovers and hiking enthusiasts.", symbol: "figure.hiking"),
    Location(name: "Isle of Islay Festival of Music and Malt", latitude: 55.6742, longitude: -6.1100, color: .red, description: "A week-long celebration of Islay’s whisky heritage and vibrant music scene. The festival features distillery tours, whisky tastings, live performances, and a lively atmosphere across the island.", symbol: "music.quarternote.3"),


    // 🔵 Points of Interest (POI)
    Location(name: "Edinburgh Castle", latitude: 55.9486, longitude: -3.1999, color: .blue, description: "A historic fortress dominating the skyline of Edinburgh from Castle Rock. It has served as a royal residence, military stronghold, and symbol of Scottish heritage, housing the Crown Jewels and the Stone of Destiny.", symbol: "crown.fill"),
    Location(name: "Arthur's Seat", latitude: 55.9445, longitude: -3.1618, color: .blue, description: "An ancient volcano and the highest point in Holyrood Park, offering panoramic views over Edinburgh. Popular for hiking, it’s also tied to myths and legends, including connections to King Arthur.", symbol: "chair.fill"),
    //[NO INFORMATION FOUND]Location(name: "Kelvingrove Art Gallery and Museum", latitude: 55.8680, longitude: -4.2906, color: .blue),
    Location(name: "The Real Mary King's Close", latitude: 55.9508, longitude: -3.1901, color: .blue, description: "A historic underground street beneath Edinburgh’s Royal Mile. Once a bustling neighborhood, it was sealed off during the plague years. Now a popular tour site, it offers a glimpse into 17th-century life and eerie urban legends.", symbol: "door.left.hand.closed"),
    Location(name: "Celtic Park", latitude: 55.8497, longitude: -4.2055, color: .blue, description: "The home stadium of Celtic Football Club in Glasgow, one of Scotland’s most iconic football grounds. Known for its passionate fans and electric match-day atmosphere, it’s a central site in Scottish football history.", symbol: "sportscourt.fill"),
    Location(name: "Culloden Battlefield", latitude: 57.4765, longitude: -4.0918, color: .blue, description: "The site of the 1746 Battle of Culloden, where Jacobite forces were defeated by the British army. Located near Inverness, it marks the end of the Jacobite uprising and is preserved as a memorial to those who fell.", symbol: "shield.pattern.checkered"),
    Location(name: "Fairy Pools", latitude: 57.2500, longitude: -6.2720, color: .blue, description: "A series of crystal-clear waterfalls and pools at the foot of the Black Cuillin mountains on the Isle of Skye. Known for their vivid blue waters, they’re a popular spot for hiking, photography, and wild swimming.", symbol: "water.waves"),
    Location(name: "Scott Monument", latitude: 55.9531, longitude: -3.1937, color: .blue, description: "A towering Gothic structure on Edinburgh’s Princes Street, built to honour Scottish author Sir Walter Scott. Visitors can climb its narrow stairs for panoramic views of the city and learn about Scott’s literary legacy.", symbol: "star.circle.fill"),
    Location(name: "Greyfriars Bobby", latitude: 55.9471, longitude: -3.1910, color: .blue, description: "The loyal Skye Terrier who famously guarded his owner’s grave for 14 years at Greyfriars Cemetery in Edinburgh. His story of devotion is commemorated by a statue near the cemetery, making him a beloved symbol of loyalty.", symbol: "dog.fill"),
    Location(name: "Ibrox Stadium", latitude: 55.8520, longitude: -4.3090, color: .blue, description: "The iconic home of Rangers Football Club in Glasgow. Known for its passionate fanbase and rich football history, Ibrox is one of Scotland's most famous and historic football grounds.", symbol: "sportscourt.fill"),
    Location(name: "Forth Bridge", latitude: 56.0000, longitude: -3.4000, color: .blue, description: "A UNESCO World Heritage Site and an engineering marvel, this iconic railway bridge spans the Firth of Forth. Completed in 1890, its distinctive red color and steel structure make it one of Scotland’s most recognized landmarks.", symbol: "table.furniture.fill"),
    Location(name: "George Square", latitude: 55.8611, longitude: -4.2500, color: .blue, description: "The central hub of Glasgow, surrounded by historic buildings and statues. It’s a popular spot for events, festivals, and gatherings, offering a mix of culture and city life.", symbol: "theatermasks.fill"),
    Location(name: "Commando Monument", latitude: 56.8887, longitude: -4.9194, color: .blue, description: "A striking memorial located near Spean Bridge, honoring the British commandos who trained in the area during World War II. The monument features a statue of a commando and offers stunning views of the surrounding Highland landscape.", symbol: "figure.stand"),

    
    // 🟢 History
    Location(name: "Palace of Holyroodhouse", latitude: 55.9525, longitude: -3.1725, color: .green, description: "The official residence of the British monarch in Scotland, located at the end of Edinburgh’s Royal Mile. Steeped in history, it’s known for its grand architecture, beautiful gardens, and connections to Scottish royalty.", symbol: "building.columns.fill"),
    Location(name: "Dunnottar Castle", latitude: 56.9450, longitude: -2.1970, color: .green, description: "A dramatic cliffside fortress on Scotland’s northeast coast, steeped in history. Once home to the Earls of Marischal, it’s famous for its stunning location and role in Scotland's medieval battles and royal history.", symbol: "mountain.2.fill"),
    Location(name: "Urquhart Castle", latitude: 57.3240, longitude: -4.4400, color: .green, description: "A historic ruin on the shores of Loch Ness, offering breathtaking views of the loch and surrounding Highlands. Once a strategic stronghold, it’s now a popular site for history lovers and those seeking a glimpse into Scotland’s past.", symbol: "star.circle.fill"),
    Location(name: "St Giles' Cathedral", latitude: 55.9499, longitude: -3.1900, color: .green, description: "A magnificent medieval church located on Edinburgh’s Royal Mile. Known for its stunning architecture, particularly its Crown Spire, it’s a key part of Scotland’s religious history and a beautiful place to explore.", symbol: "star.circle.fill"),
    Location(name: "Fort George", latitude: 57.5786, longitude: -4.0417, color: .green, description: "A large, 18th-century fortress near Inverness, built after the Jacobite rebellion to secure the Highlands. Still in use by the military today, it offers a glimpse into Scotland's military past and boasts spectacular views of the Moray Firth.", symbol: "building.columns.fill"),
    Location(name: "Rosslyn Chapel", latitude: 55.8555, longitude: -3.1611, color: .green, description: "A captivating 15th-century chapel near Edinburgh, famous for its intricate carvings and mysterious symbolism. It gained global attention through The Da Vinci Code and remains a site of fascination for history and mystery enthusiasts.", symbol: "star.circle.fill"),
    Location(name: "Balmoral Castle", latitude: 57.0406, longitude: -3.2305, color: .green, description: "The Scottish holiday home of the British royal family, located in the Cairngorms National Park. Known for its picturesque setting, the castle is surrounded by vast estates and has been a royal residence since Queen Victoria’s reign.", symbol: "star.circle.fill"),
    Location(name: "National Wallace Monument", latitude: 56.1289, longitude: -3.9375, color: .green, description: "A towering structure in Stirling, dedicated to William Wallace, the Scottish hero who led the fight for independence. The monument offers panoramic views of the surrounding area and houses exhibits about Wallace’s life and legacy.", symbol: "star.circle.fill"),
    Location(name: "Linlithgow Palace", latitude: 55.9764, longitude: -3.6000, color: .green, description: "The birthplace of Mary, Queen of Scots, and a stunning example of Renaissance architecture. Located near Edinburgh, its ruins are set beside a picturesque loch, offering a glimpse into Scotland’s royal past.", symbol: "building.columns.fill"),
    Location(name: "Culzean Castle & Country Park", latitude: 55.3565, longitude: -4.8104, color: .green, description: "A grand 18th-century castle on the Ayrshire coast, surrounded by beautiful gardens and woodlands. It offers stunning views of the Firth of Clyde and is a popular spot for history, nature, and scenic walks.", symbol: "building.columns.fill"), //fix cords pls
    Location(name: "Stirling Castle", latitude: 56.1224, longitude: -3.9461, color: .green, description: "One of Scotland’s most important historical sites, this royal fortress was the home of Scottish kings and queens, including Mary, Queen of Scots. Located atop a hill, it offers panoramic views and showcases Scotland’s medieval past.", symbol: "building.columns.fill"),
    Location(name: "Glamis Castle", latitude: 56.6225, longitude: -3.0047, color: .green, description: "A historic Scottish castle famous for its connection to the royal family and the legendary birth of Princess Margaret. Steeped in history and folklore, it’s known for its stunning architecture, beautiful grounds, and tales of hauntings.", symbol: "building.columns.fill"),
    Location(name: "Craigmillar Castle", latitude: 55.9231, longitude: -3.1314, color: .green, description: "A well-preserved medieval fortress located just outside Edinburgh. Known for its strong historical ties, including its connection to Mary, Queen of Scots, it offers visitors a glimpse into Scotland’s turbulent past with impressive ruins and scenic views.", symbol: "star.circle.fill"),
    
    // 🔷 Myths & Legends
    Location(name: "Loch Ness", latitude: 57.3229, longitude: -4.4244, color: .purple, description: "Scotland’s famous deep freshwater loch, best known for the legend of the Loch Ness Monster. Surrounded by stunning Highlands scenery, it’s a popular spot for boat tours, hiking, and exploring Urquhart Castle.", symbol: "water.waves"),
    Location(name: "Selkies Orkney Islands", latitude: 58.9835, longitude: -2.9595, color: .purple, description: "Mythical creatures from Scottish folklore, said to live as seals in the sea but shed their skins to become human on land. Orkney’s coastal waters and stories keep the legend alive.", symbol: "figure.stand"),
    Location(name: "Fingal's Cave", latitude: 56.4337, longitude: -6.3350, color: .purple, description: "A sea cave on the uninhabited Isle of Staffa, known for its unique basalt columns and natural acoustics. Its striking formation has inspired legends, music, and visitors for centuries.", symbol: "mountain.2.fill"),
    Location(name: "Corryvreckan Whirlpool", latitude: 56.1833, longitude: -5.7333, color: .purple, description: "One of the world’s most powerful whirlpools, located between Jura and Scarba. Known for its fierce tidal currents and roaring waters, it’s a dramatic natural wonder steeped in Scottish folklore.", symbol: "water.waves"),
    Location(name: "Nine Maidens of Dundee", latitude: 56.4870, longitude: -3.0041, color: .purple, description: "A local legend about nine sisters said to have been devoured by a dragon, later slain by the hero Martin. The tale is tied to ancient stone markers and Dundee’s rich folklore.", symbol: "sparkles"),
    Location(name: "Stoor Worm Orkney", latitude: 58.9825, longitude: -2.9595, color: .purple, description: "A giant sea serpent from Scottish mythology, said to terrorize villages until it was defeated by the hero Assipattle. Some legends suggest it inspired the tale of the Loch Ness Monster.", symbol: "water.waves"),
    Location(name: "Gorbals Vampire Glasgow", latitude: 55.8460, longitude: -4.2580, color: .purple, description: "A Glasgow urban legend from the 1950s about a seven-foot-tall, iron-toothed vampire said to haunt the Southern Necropolis. The myth sparked a mass hunt by local children and debates over horror comics’ influence.", symbol: "figure.stand"),
    Location(name: "Ghost Piper of Clanyard Bay", latitude: 54.7000, longitude: -4.9500, color: .purple, description: "A legend of a piper who vanished while exploring an underground cave near Clanyard Bay. His ghostly music is said to still echo from beneath the cliffs, haunting the coastline.", symbol: "music.quarternote.3"),
    Location(name: "Robert the Bruce and the Spider Bruce’s Cave", latitude: 55.0240, longitude: -3.0780, color: .purple, description: "A legend telling how Robert the Bruce, hiding in a cave, watched a spider persistently spin its web. Inspired by its determination, he rallied to win Scotland’s freedom at Bannockburn.", symbol: "mountain.2.fill"),
    Location(name: "The Ghosts of Glamis Castle", latitude: 56.6225, longitude: -3.0003, color: .purple, description: "Known for its haunted history, Glamis Castle is said to be home to several spirits, including the mysterious >>Monster of Glamis<< and the ghost of Lady Janet Douglas, executed for witchcraft. The castle’s eerie legends have intrigued visitors for centuries.", symbol: "questionmark.app.fill"),
    Location(name: "The Green Lady of Crathes Castle", latitude: 57.0671, longitude: -2.4886, color: .purple, description: "A ghostly figure said to haunt Crathes Castle near Aberdeen. The Green Lady is believed to be the spirit of a former inhabitant, often seen wearing a green gown. She’s linked to a tragic love story, and her haunting presence is said to bring both fear and fascination to those who visit.", symbol: "figure.stand"),
    Location(name: "The White Lady of St Andrews Cathedral", latitude: 56.3395, longitude: -2.7969, color: .purple, description: "A ghostly figure dressed in white, said to haunt the ruins of St Andrews Cathedral. Legend has it she is the spirit of a young woman searching for her lost lover, whose tragic fate is tied to the cathedral’s history.", symbol: "figure.stand"),
    Location(name: "The Mermaid of Assynt", latitude: 58.1700, longitude: -5.1000, color: .purple, description: "A legend of a mermaid said to inhabit the waters near Assynt. According to folklore, she was captured by a local man but later escaped, cursing the land as she returned to the sea.", symbol: "water.waves")

]
